spring:
    application:
        name: jobtrigger
    jackson:
        serialization:
            INDENT_OUTPUT: true
server:
    servlet:
        context-path: /jobtrigger
    port: 8080
edison:
    gracefulshutdown:
        enabled: false
    jobtrigger:
        jobresults:
            max: 1000
        scheduler:
            poolsize: 10
        security:
            basicAuthUser: someUser
            basicAuthPasswd: somePassword
    metrics:
        slf4j:
            logger: de.otto.edison.jobtrigger
    status:
        redirect-internal:
            enabled: true
management:
    context-path: /internal
    security:
        enabled: false
    endpoint:
        metrics:
            enabled: false
        loggers:
            enabled: true
    health:
        diskspace:
            enabled: false
    endpoints:
        web:
            exposure:
                include: '*'


